/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as MovesIndexRouteImport } from './routes/moves.index'
import { Route as MovesNameRouteImport } from './routes/moves.$name'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlaySilhouetteRouteImport } from './routes/play.silhouette'
import { Route as PokemonIndexRouteImport } from './routes/pokemon.index'
import { Route as PokemonNameRouteImport } from './routes/pokemon.$name'
import { Route as TypesIndexRouteImport } from './routes/types.index'
import { Route as TypesNameRouteImport } from './routes/types.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MovesIndexRoute = MovesIndexRouteImport.update({
  id: '/moves/',
  path: '/moves/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovesNameRoute = MovesNameRouteImport.update({
  id: '/moves/$name',
  path: '/moves/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaySilhouetteRoute = PlaySilhouetteRouteImport.update({
  id: '/play/silhouette',
  path: '/play/silhouette',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonIndexRoute = PokemonIndexRouteImport.update({
  id: '/pokemon/',
  path: '/pokemon/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonNameRoute = PokemonNameRouteImport.update({
  id: '/pokemon/$name',
  path: '/pokemon/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesIndexRoute = TypesIndexRouteImport.update({
  id: '/types/',
  path: '/types/',
  getParentRoute: () => rootRouteImport,
} as any)
const TypesNameRoute = TypesNameRouteImport.update({
  id: '/types/$name',
  path: '/types/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/moves/$name': typeof MovesNameRoute
  '/play/silhouette': typeof PlaySilhouetteRoute
  '/pokemon/$name': typeof PokemonNameRoute
  '/types/$name': typeof TypesNameRoute
  '/moves/': typeof MovesIndexRoute
  '/play/': typeof PlayIndexRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/types/': typeof TypesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/moves/$name': typeof MovesNameRoute
  '/play/silhouette': typeof PlaySilhouetteRoute
  '/pokemon/$name': typeof PokemonNameRoute
  '/types/$name': typeof TypesNameRoute
  '/moves': typeof MovesIndexRoute
  '/play': typeof PlayIndexRoute
  '/pokemon': typeof PokemonIndexRoute
  '/types': typeof TypesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/moves/$name': typeof MovesNameRoute
  '/play/silhouette': typeof PlaySilhouetteRoute
  '/pokemon/$name': typeof PokemonNameRoute
  '/types/$name': typeof TypesNameRoute
  '/moves/': typeof MovesIndexRoute
  '/play/': typeof PlayIndexRoute
  '/pokemon/': typeof PokemonIndexRoute
  '/types/': typeof TypesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/moves/$name'
    | '/play/silhouette'
    | '/pokemon/$name'
    | '/types/$name'
    | '/moves/'
    | '/play/'
    | '/pokemon/'
    | '/types/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/moves/$name'
    | '/play/silhouette'
    | '/pokemon/$name'
    | '/types/$name'
    | '/moves'
    | '/play'
    | '/pokemon'
    | '/types'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/moves/$name'
    | '/play/silhouette'
    | '/pokemon/$name'
    | '/types/$name'
    | '/moves/'
    | '/play/'
    | '/pokemon/'
    | '/types/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MovesNameRoute: typeof MovesNameRoute
  PlaySilhouetteRoute: typeof PlaySilhouetteRoute
  PokemonNameRoute: typeof PokemonNameRoute
  TypesNameRoute: typeof TypesNameRoute
  MovesIndexRoute: typeof MovesIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  PokemonIndexRoute: typeof PokemonIndexRoute
  TypesIndexRoute: typeof TypesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moves/': {
      id: '/moves/'
      path: '/moves'
      fullPath: '/moves/'
      preLoaderRoute: typeof MovesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moves/$name': {
      id: '/moves/$name'
      path: '/moves/$name'
      fullPath: '/moves/$name'
      preLoaderRoute: typeof MovesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/silhouette': {
      id: '/play/silhouette'
      path: '/play/silhouette'
      fullPath: '/play/silhouette'
      preLoaderRoute: typeof PlaySilhouetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/': {
      id: '/pokemon/'
      path: '/pokemon'
      fullPath: '/pokemon/'
      preLoaderRoute: typeof PokemonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$name': {
      id: '/pokemon/$name'
      path: '/pokemon/$name'
      fullPath: '/pokemon/$name'
      preLoaderRoute: typeof PokemonNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/': {
      id: '/types/'
      path: '/types'
      fullPath: '/types/'
      preLoaderRoute: typeof TypesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/types/$name': {
      id: '/types/$name'
      path: '/types/$name'
      fullPath: '/types/$name'
      preLoaderRoute: typeof TypesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MovesNameRoute: MovesNameRoute,
  PlaySilhouetteRoute: PlaySilhouetteRoute,
  PokemonNameRoute: PokemonNameRoute,
  TypesNameRoute: TypesNameRoute,
  MovesIndexRoute: MovesIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  PokemonIndexRoute: PokemonIndexRoute,
  TypesIndexRoute: TypesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
